#!/opt/python/bin/python2.6

import sys, os
parent_dir, dir_name = os.path.split(os.path.split(os.path.abspath(__file__))[0])
if dir_name == 'nesoni_scripts':
    sys.path.insert(0, parent_dir)

import nesoni
from nesoni import grace, config

try:
    sys.exit(nesoni.main(sys.argv[1:]))

except grace.Help_shown:
    sys.exit(1)

except Exception:
    config.report_exception()
    sys.exit(1) 